---
name: Build
'on':
  push:
    branches:
    - main
    tags:
    - "**"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: "${{ github.actor }}"
        password: "${{ github.token }}"
    - name: Make
      env:
        PKGFORGE_STATEFILE: "/tmp/pkgforge"
        GITHUB_TOKEN: "${{ github.token }}"
      run: make
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: pkg/image
      if: startsWith(github.ref, 'refs/tags/')
    - name: Post to hook-exporter
      run: "./.github/exporter.sh"
      env:
        EXPORTER_TOKEN: "${{ secrets.EXPORTER_TOKEN }}"
        JOB_STATUS: "${{ job.status }}"
      if: always() && github.ref == 'refs/heads/main'
